import type { AppViewState, ProposalOutcomeState, SimulationState } from "@/types/hegel-triangle";

export const PROPOSAL_OUTCOME_STATES: readonly ProposalOutcomeState[] = [
  "pending",
  "accepted",
  "rejected",
  "blocked",
  "vacuous",
  "promising",
];

export function createInitialSimulationState(): SimulationState {
  return {
    runState: "paused",
    activeTick: 0,
    activeFragmentId: undefined,
    activeProposalId: undefined,
    persistentConfig: {
      promoteOnlyAccepted: true,
      keepPromisingItems: false,
    },
    persistent: {
      promotedFragmentIds: [],
      promotedProposalIds: [],
      keptPromisingProposalIds: [],
      acceptedConnectionIds: [],
      acceptedEdgeIds: [],
      theoremStubs: [],
      definitionStubs: [],
    },
    proposalQueue: [],
    acceptedHistory: [],
    rejectedHistory: [],
    replayLog: [],
    fragments: {},
    vertices: {},
    exposedConnections: {},
    edges: {},
    proposals: {},
    leanTasks: {},
    proofAttempts: {},
  };
}

export function createDefaultAppViewState(): AppViewState {
  return {
    selectedFragmentId: undefined,
    selectedVertexId: undefined,
    selectedEdgeId: undefined,
    selectedProposalId: undefined,
    hoveredFragmentId: undefined,
    selectionMode: "none",
    viewportMode: "fit",
    renderMode: "status",
    showFragmentLabels: true,
    showGraphEdges: true,
    showAcceptedOverlay: true,
    showRejectedOverlay: true,
    showPersistentLayer: true,
    showProposalLabels: true,
    showEdgeLabels: false,
    inspectorTab: "fragment",
    activeMainView: "triangle",
    modulePanels: {
      informationGeometryLabOpen: false,
      informationGeometryLabTab: "patches",
    },
    semeiotic: {
      semeioticsEnabled: false,
      semeioticAutoAnnotate: false,
      selectedDialecticalMomentId: undefined,
      semeioticOverlayVisible: false,
      semeioticGrammarPanelOpen: false,
      semeioticTreeFilter: "all",
      semeioticSummaryMode: "compact",
      showOnlyAnnotatedMoves: false,
      activeSemeioticTickWindow: 8,
      logRawOutputs: true,
      influencesPromiseProfile: false,
      selectedLens: "triadic",
      showTreeBadges: true,
      showLogBadges: true,
    },
    informationGeometryLab: {
      selectedIGViewMode: "localPatch",
      selectedGeometryMode: "quadraticBregman",
      selectedFragmentId: undefined,
      selectedProposalId: undefined,
      selectedTick: 0,
      selectedChartKind: "theta",
      voronoiGridResolution: 18,
      voronoiSiteSource: "nearbyFragments",
      liftedProjectionAngle: 34,
      liftedHeightScale: 1,
      accumulationTrailLength: 8,
      accumulationMode: "both",
      barycenterSourceMode: "activeNeighborhood",
      barycenterWeightMode: "uniform",
      barycenterTickWindow: 6,
      selectedFlowMode: "proposalFlow",
      regressionEnabled: false,
      regressionTargetMode: "activeProposalHistory",
      regressionDisplayMode: "fittedCurve",
      regressionTickWindow: 8,
      flowVectorDensity: 2,
      flowVectorScale: 1,
      selectedScalarField: "divergence",
      colorScaleMode: "sequential",
      normalizationMode: "local",
      autoFollowActiveFragment: true,
      freezeCurrentSnapshot: false,
      compareWithPreviousTick: false,
      showVoronoiSites: true,
      showVoronoiBoundaries: true,
      showLiftedSurface: true,
      showLiftedStems: true,
      showLiftedFootprint: true,
      showGeodesics: true,
      showNucleation: true,
      showCatastropheMarkers: true,
      showBarycenter: true,
      showBarycenterTrail: false,
      showFlowVectors: false,
      showFlowTrails: false,
      animateFlowOverTicks: false,
      showResidualMarkers: false,
      showAccumulationHistory: true,
    },
    replay: {
      mode: "live",
      isPlaying: false,
      playbackGranularity: "event",
      tick: 0,
      selectedEventId: undefined,
      logFilter: "all",
      providerFilter: "all",
      liveObservedEventId: undefined,
    },
  };
}
